# Generated by Django 5.1.1 on 2024-11-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj1', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
